import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import GlowingCursor from "@/components/GlowingCursor";
import Firebase from "@/components/Firebase";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark antialiased `}>
        <GlowingCursor />
        <Firebase />

        {children}
      </body>
    </html>
  );
}
